---
title: "Discovery"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


I have recently discovered that you can make multiple cursors in r, this is very useful for extremely specific situations

I have recently discovered that you can make multiple cursors in r, this is very useful for extremely specific situations

I have recently discovered that you can make multiple cursors in r, this is very useful for extremely specific situations

I have recently discovered that you can make multiple cursors in r, this is very useful for extremely specific situations

I have recently discovered that you can make multiple cursors in r, this is very useful for extremely specific situations

I have recently discovered that you can make multiple cursors in r, this is very useful for extremely specific situations

I have recently discovered that you can make multiple cursors in r, this is very useful for extremely specific situations

I have recently discovered that you can make multiple cursors in r, this is very useful for extremely specific situations

I have recently discovered that you can make multiple cursors in r, this is very useful for extremely specific situations

I have recently discovered that you can make multiple cursors in r, this is very useful for extremely specific situations

I have recently discovered that you can make multiple cursors in r, this is very useful for extremely specific situations

I have recently discovered that you can make multiple cursors in r, this is very useful for extremely specific situations

I have recently discovered that you can make multiple cursors in r, this is very useful for extremely specific situations

I have recently discovered that you can make multiple cursors in r, this is very useful for extremely specific situations

I have recently discovered that you can make multiple cursors in r, this is very useful for extremely specific situations

I have recently discovered that you can make multiple cursors in r, this is very useful for extremely specific situations

I have recently discovered that you can make multiple cursors in r, this is very useful for extremely specific situations

I have recently discovered that you can make multiple cursors in r, this is very useful for extremely specific situations

I have recently discovered that you can make multiple cursors in r, this is very useful for extremely specific situations

I have recently discovered that you can make multiple cursors in r, this is very useful for extremely specific situations

I have recently discovered that you can make multiple cursors in r, this is very useful for extremely specific situations

I have recently discovered that you can make multiple cursors in r, this is very useful for extremely specific situations

I have recently discovered that you can make multiple cursors in r, this is very useful for extremely specific situations

I have recently discovered that you can make multiple cursors in r, this is very useful for extremely specific situations

I have recently discovered that you can make multiple cursors in r, this is very useful for extremely specific situations

I have recently discovered that you can make multiple cursors in r, this is very useful for extremely specific situations

I have recently discovered that you can make multiple cursors in r, this is very useful for extremely specific situations

I have recently discovered that you can make multiple cursors in r, this is very useful for extremely specific situations

I have recently discovered that you can make multiple cursors in r, this is very useful for extremely specific situations

I have recently discovered that you can make multiple cursors in r, this is very useful for extremely specific situations

I have recently discovered that you can make multiple cursors in r, this is very useful for extremely specific situations

I have recently discovered that you can make multiple cursors in r, this is very useful for extremely specific situations

I have recently discovered that you can make multiple cursors in r, this is very useful for extremely specific situations

I have recently discovered that you can make multiple cursors in r, this is very useful for extremely specific situations

I have recently discovered that you can make multiple cursors in r, this is very useful for extremely specific situations

I have recently discovered that you can make multiple cursors in r, this is very useful for extremely specific situations

I have recently discovered that you can make multiple cursors in r, this is very useful for extremely specific situations

I have recently discovered that you can make multiple cursors in r, this is very useful for extremely specific situations

I have recently discovered that you can make multiple cursors in r, this is very useful for extremely specific situations







































































